version: 1.4.0
Directory_Settings:
  use_default_directory: true
  custom_default_directory: ''
Popup_Settings:
  playlist_confirmation: true
  file_downloaded: true
Miscellaneous_Settings:
  default_as_audio: false
  color_theme: DarkAmber
